// <auto-generated />
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyProduct("Weave")]
[assembly: AssemblyCopyright("Copyright © 2013 John Gietzen")]
[assembly: ComVisible(false)]
[assembly: AssemblyVersion("1.1.0.0")]
[assembly: AssemblyFileVersion("1.1.0.0")]
