// <auto-generated />

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("Weave")]
[assembly: AssemblyDescription("")]
[assembly: Guid("4ca50bf8-ffbc-4036-9963-10972b2b38c8")]
[assembly: NeutralResourcesLanguageAttribute("en-US")]
[assembly: CLSCompliant(true)]
