// <auto-generated />

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("Weave.Tests")]
[assembly: AssemblyDescription("")]
[assembly: Guid("75441ed3-6f3e-4cab-8f96-9f57734b1859")]
[assembly: NeutralResourcesLanguageAttribute("en-US")]
[assembly: CLSCompliant(true)]
