
// -----------------------------------------------------------------------
// <auto-generated>
//   This code was generated by Weave 1.0.0.0
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated.
// </auto-generated>
// -----------------------------------------------------------------------

namespace Weave.Compiler
{
    using System.IO;
    
        using Weave.Expressions;
    

     partial class Templates
    {
        [System.CodeDom.Compiler.GeneratedCode("Weave", "1.0.0.0")]
        public void RenderEachTag(EachTag model, TextWriter writer)
        {
            
    var flag = this.CreateVariable("_flag");

writer.Write("\r\n\r\n");


    
    
    if ( model.NoneBody != null)

{
    writer.Write("\r\n    bool ");
writer.Write(flag );
writer.Write(";\r\n");

}
    
writer.Write("\r\n\r\nforeach (var ");
writer.Write(model.Expression );
writer.Write(")\r\n{\r\n    ");


    
    
    if ( model.NoneBody != null)

{
    writer.Write("\r\n        ");
writer.Write(flag );
writer.Write(" = true;\r\n    ");

}
    
writer.Write("\r\n\r\n    ");
 this.WalkElements(model.Body); 
writer.Write("\r\n}\r\n\r\n");


    
    
    if ( model.NoneBody != null)

{
    writer.Write("\r\n    if (!");
writer.Write(flag );
writer.Write(")\r\n    {\r\n        ");
 this.WalkElements(model.NoneBody); 
writer.Write("\r\n    }\r\n");

}
    

        }
    }
}