// -----------------------------------------------------------------------
// <auto-generated>
//   This code was generated by Weave 2.1.0.0
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated.
// </auto-generated>
// -----------------------------------------------------------------------

namespace
    #line 1 "_config.weave"
           Weave.Compiler
    #line default
{
    using System;
    using System.IO;
    using
        #line 2 "_config.weave"
       Weave.Expressions
        #line default
        ;

    partial class
    Templates
    {
        [System.CodeDom.Compiler.GeneratedCode("Weave", "2.1.0.0")]
        public
        void
        RenderEchoTag
            (
            #line 1 "EchoTag.weave"
       EchoTag
            #line default
            model, TextWriter writer, string indentation = null)
        {
            var __encode = new Func<object, string>(
                #line 4 "_config.weave"
        ToLiteral
                #line default
                );
            var __originalIndentation = indentation = indentation ?? string.Empty;
            if (
                #line 3 "EchoTag.weave"
     model.Encoded
                #line default
                )
            {
                writer.Write(indentation);
                writer.Write("writer.Write(__encode(");
                writer.WriteLine();
                indentation = __originalIndentation + "    ";
                var __model0 =
                    #line 5 "EchoTag.weave"
                      model.Expression
                    #line default
                    ;
                RenderCode(__model0, writer, indentation);
                writer.Write(indentation);
                writer.Write("));");
                writer.WriteLine();
            }
            else
            {
                writer.Write(indentation);
                writer.Write("writer.Write(");
                writer.WriteLine();
                indentation = __originalIndentation + "    ";
                var __model1 =
                    #line 9 "EchoTag.weave"
                      model.Expression
                    #line default
                    ;
                RenderCode(__model1, writer, indentation);
                writer.Write(indentation);
                writer.Write(");");
                writer.WriteLine();
            }
        }
    }
}
