
// -----------------------------------------------------------------------
// <auto-generated>
//   This code was generated by Weave 1.0.0.0
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated.
// </auto-generated>
// -----------------------------------------------------------------------

namespace 

#line 1 "IfTag.weave"
           Weave.Compiler
#line default


{
    using System.IO;
        using 

#line 4 "IfTag.weave"
       Weave.Expressions
#line default

;

    
    
 partial class 
    Templates

    {
        [System.CodeDom.Compiler.GeneratedCode("Weave", "1.0.0.0")]
        public void 

#line 2 "IfTag.weave"
            RenderIfTag
#line default

(

#line 3 "IfTag.weave"
       IfTag
#line default

 model, TextWriter writer)
        {
            

#line 6 "IfTag.weave"
   var first = true; 
#line default

writer.Write("\r\n");



foreach (var 

#line 7 "IfTag.weave"
       branch in model.Branches
#line default

)
{

    
        if (

#line 8 "IfTag.weave"
         !first
#line default

)
{
    writer.Write("        else");
writer.Write("\r\n");

}
    
writer.Write("    ");


#line 11 "IfTag.weave"
       this.WalkBranch(branch); 
#line default

writer.Write("\r\n");
writer.Write("    ");


#line 12 "IfTag.weave"
       first = false; 
#line default

writer.Write("\r\n");

}


        }
    }
}