// -----------------------------------------------------------------------
// <auto-generated>
//   This code was generated by Weave 2.1.0.0
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated.
// </auto-generated>
// -----------------------------------------------------------------------

namespace
    #line 1 "_config.weave"
           Weave.Compiler
    #line default
{
    using System;
    using System.IO;
    using
        #line 2 "_config.weave"
       Weave.Expressions
        #line default
        ;

    partial class
    Templates
    {
        [System.CodeDom.Compiler.GeneratedCode("Weave", "2.1.0.0")]
        public
        void
        #line 1 "Indentation.weave"
            UpdateIndentation
        #line default
            (
            #line 2 "Indentation.weave"
       Element
            #line default
            model, TextWriter writer, string indentation = null)
        {
            var __encode = new Func<object, string>(
                #line 4 "_config.weave"
        ToLiteral
                #line default
                );
            var __originalIndentation = indentation = indentation ?? string.Empty;
            var __temp0 = indentation;
            #line 4 "Indentation.weave"
  
    Tuple<Element, string> indent;
    this.indentation.TryGetValue(model, out indent);

            #line default
            indentation = __temp0;
            if (
                #line 8 "Indentation.weave"
     indent != null
                #line default
                )
            {
                writer.Write(indentation);
                writer.Write("indentation = ");
                writer.Write(
                    #line 9 "Indentation.weave"
                      this.indentationBase 
                    #line default
                    );
                if (
                    #line 9 "Indentation.weave"
                                                  indent.Item2.Length > 0
                    #line default
                    )
                {
                    writer.Write(" + ");
                    writer.Write(__encode(
                        #line 9 "Indentation.weave"
                                                                                  indent.Item2 
                        #line default
                        ));
                }
                writer.Write(";");
                writer.WriteLine();
            }
        }
    }
}
