// -----------------------------------------------------------------------
// <auto-generated>
//   This code was generated by Weave 1.2.0.0
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated.
// </auto-generated>
// -----------------------------------------------------------------------

namespace
    #line 1 "_config.weave"
           Weave.Compiler
    #line default
{
    using System;
    using System.IO;
    using
        #line 2 "_config.weave"
       Weave.Expressions
        #line default
        ;

    partial class
    Templates
    {
        [System.CodeDom.Compiler.GeneratedCode("Weave", "1.2.0.0")]
        public
        void
        RenderTextElement
            (
            #line 1 "TextElement.weave"
       TextElement
            #line default
            model, TextWriter writer, string indentation = null)
        {
            var __encode = new Func<object, string>(
                #line 4 "_config.weave"
        ToLiteral
                #line default
                );
            var __originalIndentation = indentation = indentation ?? string.Empty;
            writer.Write(indentation);
            writer.Write("writer.Write(");
            writer.Write(__encode(
                #line 3 "TextElement.weave"
                 model.Value 
                #line default
                ));
            writer.Write(");");
            writer.WriteLine();
        }
    }
}
